### ISSUE TITLE
Descrição do componente interativo.

### ISSUE THREAD

**Issue by matheusgr** [deborafb/DevWeb#1]
Podes colocar a descrição do componente interativo?

Talvez na listagem de CD ter tags ou uma organização de tabela que identifique os cantores e agrupe dessa forma, e/ou que permita vc arrastar para favoritar. Precisa ter um componente assim, de natureza mais interativa. Essa ação precisa também afetar outros componentes em tela. (exemplo, ao favoritar, aumenta o numero de itens favoritos, e uma listagem de autores prediletos).

**Comment by deborafb** [comment]
Feito
