### ISSUE TITLE
Organizar as imagens em uma pasta dedicada para elas

### ISSUE THREAD

**Issue by vitoria** [deborafb/DevWeb#3]
Opa, Débora!

Muito bacana a ideia do seu projeto.

Criar um ecommerce assim do zero vai ser um desafio e tanto, o que é muito legal!

Só para melhorar a estruturação do seu projeto, sugiro mover as imagens para uma pasta específica para elas (e.g. `images/`), assim não deixaria misturado os arquivos de HTML com imagens e tudo mais.

**Comment by deborafb** [comment]
Feito
